### ISSUE TITLE
Error while building image 

### ISSUE THREAD

**Issue by anayyar82** [RedwanAlkurdi/Lakehouse-Spark-Hive-Delta-Minio-Trino-Zeppelin#1]
=> ERROR [spark-worker:3.0.1-hadoop3.2 internal] load metadata for docker.io/library/spark-base:3.0.1-hadoop3.2                                         1.3s
 => CANCELED [hive-metastore:latest internal] load metadata for docker.io/library/openjdk:8u242-jre                                                      1.2s
 => CANCELED [spark-base:3.0.1-hadoop3.2 internal] load metadata for docker.io/library/alpine:3.10                                                       1.2s
 => [minio/mc internal] load metadata for docker.io/minio/mc:latest                                                                                      0.0s
 => [minio/mc 1/2] FROM docker.io/minio/mc                                                                                                               0.0s
 => CANCELED [zeppelin internal] load metadata for docker.io/apache/zeppelin:0.9.0                                                                       1.1s
 => CANCELED [minio/mc 2/2] RUN microdnf install wget                                                                                                    1.2s
------
 > [spark-worker:3.0.1-hadoop3.2 internal] load metadata for docker.io/library/spark-base:3.0.1-hadoop3.2:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

**Comment by RedwanAlkurdi** [comment]
hi @anayyar82,
there is no spark-base docker hub repo. However, you are trying to pull the image. Therefore, if you check the docker files, i am building the spark-base, spark-worker, and spark-master from scratch.

the images should be built automatically. However, if it didn't work out. try building the docker images locally, before trying the docker-compose command.

**Comment by RedwanAlkurdi** [comment]
@anayyar82 did you issue get resolved?

**Comment by RedwanAlkurdi** [comment]
closed due to being irresponsive.
